import React, { useCallback, useEffect, useState } from 'react';

import { getAnalyticsAlerts, type AnalyticsAlert } from '@/api/client';

interface TeacherDashboardProps {
  idToken: string;
}

const TeacherDashboard: React.FC<TeacherDashboardProps> = ({ idToken }) => {
  const [alerts, setAlerts] = useState<AnalyticsAlert[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const loadAlerts = useCallback(async () => {
    setLoading(true);
    try {
      const response = await getAnalyticsAlerts(idToken);
      setAlerts(response.alerts);
      setError(null);
    } catch (err) {
      console.error('Failed to load analytics alerts', err);
      setError(err instanceof Error ? err.message : 'Unable to load alerts');
    } finally {
      setLoading(false);
    }
  }, [idToken]);

  useEffect(() => {
    void loadAlerts();
  }, [loadAlerts]);

  return (
    <div>
      <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between mb-6">
        <div>
          <h2 className="text-2xl font-semibold text-white">AI Alerts</h2>
          <p className="text-sm text-slate-400">Prioritized student risk signals generated by the analytics agent.</p>
        </div>
        <button
          type="button"
          onClick={() => void loadAlerts()}
          disabled={loading}
          className="inline-flex items-center justify-center rounded-md bg-indigo-500 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-400 disabled:opacity-50"
        >
          {loading ? 'Refreshing...' : 'Refresh Insights'}
        </button>
      </div>

      {error && <p className="mb-4 rounded-md border border-red-600 bg-red-950/40 px-4 py-2 text-sm text-red-200">{error}</p>}

      {loading && alerts.length === 0 ? (
        <p className="text-slate-400">Loading the latest insights...</p>
      ) : alerts.length === 0 ? (
        <p className="text-slate-400">No active risk signals detected. Great job keeping the class on track!</p>
      ) : (
        <div className="space-y-4">
          {alerts.map((alert, index) => (
            <article key={`${alert.studentId}-${index}`} className="rounded-xl border border-slate-800 bg-slate-900/70 p-5 shadow-lg">
              <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <p className="text-lg font-semibold text-white">{alert.studentName || alert.studentId}</p>
                  <p className="text-xs uppercase tracking-wide text-slate-400">Student ID: {alert.studentId}</p>
                </div>
                <span className="inline-flex items-center rounded-full bg-pink-500/20 px-3 py-1 text-sm font-semibold text-pink-200">
                  Risk Score: {alert.riskScore}
                </span>
              </div>
              <p className="mt-4 text-base text-slate-100">{alert.aiSummary || 'AI summary unavailable. Review signals below.'}</p>
              <div className="mt-4">
                <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Signals</p>
                <ul className="mt-2 space-y-2 text-sm text-slate-200">
                  {alert.signals.map((signal, signalIndex) => (
                    <li key={`${alert.studentId}-signal-${signalIndex}`} className="rounded-md bg-slate-800/80 px-3 py-2">
                      <span className="font-semibold capitalize text-indigo-200">{signal.category}:</span> {signal.description}
                    </li>
                  ))}
                </ul>
              </div>
            </article>
          ))}
        </div>
      )}
    </div>
  );
};

export default TeacherDashboard;
